projects:
  amazonclone:
    schemaPath: 'G:/PIAIC/Bootcamp2020/React-Native/AmazonClone/graphql/schema.json'
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
